[[headers]]
  for = "/models/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"

[[headers]]
  for = "*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"